"""add phone number

Revision ID: 3e2c2fb0dcd6
Revises: 1da8d9579b58
Create Date: 2022-12-26 11:24:22.073493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2c2fb0dcd6'
down_revision = '1da8d9579b58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_num', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_num')
    # ### end Alembic commands ###
